global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eventflow-api'
    static_configs:
      - targets: ['api:8001']
        labels:
          service: 'api'
  
  - job_name: 'eventflow-workers'
    static_configs:
      - targets: ['worker:8001']
        labels:
          service: 'worker'
